<?php
	// this is the default template all pages at www.lugbe.ch
	// are built upon.

	// markus@wernig.net

	// define some variables that will be used by the included file

	$page_title = "LugBE Veranstaltungen";
	$author = "webmaster lugbe ch";
	$changed_by = "";
	$create_date = "";
	$change_date = "";

	// additional keywords for search engines

	$additional_keywords= "";
	$special_css_style = "";
	$special_header = "";

	// the documet root. we use file system paths for performance.
	// ATTENTION: this may change!! Maybe we want an URL?

	$document_root = "/www/doc/lugbe/www.lugbe.ch";

	// this will be included in the header

	$special_header_include_file_path ="";

	// this will be included at the beginning of the body

	$special_body_include_file_path =""; 

	// if we include JS, this will become <SCRIPT LANGUAGE="Javascript" SRC="$javascript_src_file_path"> </SCRIPT>

	$javascript_src_file_path ="";

	// ***********************
	
	// now include the headers
	// change the path here if you want to include another header

	$header_include_file_path = "$document_root/include/header_include.tmpl";

	include $header_include_file_path;

	/* Read in the base configuration */

	/* ADJUST THIS !!! */

	if (!isset($BASEDIR)) {
        	$BASEDIR = "..";
	}

	require_once("$BASEDIR/conf/events.conf");

	if(!isset($COOKIE_DOMAIN)) {
		$COOKIE_DOMAIN = $_SERVER['SERVER_NAME'];
	}
	if(!isset($_COOKIE[$COOKIE_NAME]) && (isset($_REQUEST['submit_anmelden']) || isset($_REQUEST['propose_eins']) || isset($_REQUEST['propose_zwei']))) {
		$r=sendCookie($COOKIE_NAME,$COOKIE_DOMAIN,3600);
	}

?>


<!-- HEADER END <<<<<<<<<
*************************
CONTENT START -->

<LINK REL='stylesheet' MEDIA='screen' TYPE='text/css' HREF='/src/events.css'>

<?php
	include "$document_root/include/events.tmpl";
?>

<!-- CONTENT END <<<<<<<<<
************************** 
FOOTER START -->


<?php 
	// this will be included in the footer

	$special_footer_include_file_path ="";

	// now include the footers
	// change the path here if you want to include another footer

	$footer_include_file_path = "$document_root/include/footer_include.tmpl";

	include $footer_include_file_path;
?>	    
